services:
  - type: web
    name: career-advisor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main_app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0